### ISSUE TITLE
Merchant Ore Revision

### ISSUE THREAD

**Issue by Steviegt6** [valkyrienyanko/MerchantsPlus#2]
**Describe the bug**
The merchant sells copper and iron ore for 1 gold each.

**To Reproduce**
1. Go to the merchant.
2. Open his shop.
3. Cycle over to ores.'
4. Open up ores.
5. Both copper and iron ore cost 1 gold coin each.

**Expected behavior**
I expected a much cheaper price.

**Comment by valkyrienyanko** [comment]
What kind of price were you hoping for?

**Comment by valkyrienyanko** [comment]
That's very cheaty, don't think I'm going to do that.

**Comment by Steviegt6** [comment]
I just want you to lower the price from one gold coin. :p
