### ISSUE TITLE
Nurse's shop menu won't open

### ISSUE THREAD

**Issue by TinyDeskEngi** [valkyrienyanko/MerchantsPlus#3]
**Describe the bug**
I talk to the nurse to open her shop menu but whenever I do an action that would bring up the shop icon, it would show up for a short moment then disappear. 

**To Reproduce**
1. Speak to the Nurse.
2. Click to bring up the icon that shows "Healing       Cycle Shop"
3. See error

**Expected behavior**
I expected to see the shop menu like every other NPC but the nurse's shop won't show up long enough for it to open up.

**Comment by valkyrienyanko** [comment]
Tested and works fine in both single / multi with only merchants+ mod enabled. Try creating a new world and having only the merchants+ mod enabled and see if the issue still persists. If not than try and figure out which mod is conflicting.

**Comment by valkyrienyanko** [comment]
Issuer did not reply, closing thread.
